### ISSUE TITLE
Cannot Get Image from API

### ISSUE THREAD

**Issue by ghost** [Waifu-pics/waifu-api#62]
Yo so I'm trying to build a command to get a waifu image from the waifu.pics api in my discord bot but i have no idea what format to string the url into from json.

here is my current code:

```ts
import * as config from '../../modules/config';

const group = config.CLIENT.INTERACTION_COMMANDS;

group.register(
  {
    name: 'waifu',
    description: 'Get a waifu image from waifu.pics.',
    options: (opts) => ({
      type: opts.string({
        name: 'type',
        description: 'Select an image type.',
        required: true,
        choices: ['sfw', 'nsfw'],
      }),
    }),
  },
  async (interaction, { type }) => {

    const req = await fetch(`https://waifu.pics/${type}/waifu`);
    const data = await req.json();
    const url = data['image'][0]['url'];

    const embed = new discord.Embed()
      .setDescription(`Direct Link: [Link](${url})`)
      .setImage({ url: url })
      .setTimestamp(new Date().toISOString())
      .setColor(config.COLOR.BLUE)
      .setFooter({
        text: config.FOOTER.TEXT,
        iconUrl: config.FOOTER.ICON,
      });
    await interaction.respond({ embeds: [embed] }).catch((e) => {
      console.log(
        `>> | (${e.code}) ${e.name}: ${e.message} \n------------------------------------------------------------\n${e.stack}`
      );
      interaction.respond(
        ":face_with_spiral_eyes: Something went wrong. Don't blame me... blame the baka who built me..."
      );
    });
  }
);
```

The above code throws the following error:
```ts
Error executing slash command! SyntaxError: Unexpected token < in JSON at position 0
    at parse (<anonymous>)
    at JSON.value (pylon.js:61:22)
    at ResponsePolyfill.json (pylon.js:1300:23)
    at async SlashCommand.handler (script-369598454818672640.js:1988:22)
    at async SlashCommand._execute (discord.js:3824:25)
    at async discord.js:4017:25
 ```
 
 I've also tried using
 
```ts
 const req = await fetch(`https://waifu.pics/${type}/waifu`);
 const url = req['url'][0];
```

However that one triggers my error handler and throws this error:
```ts
>> | (50035) discord.ApiError: Invalid Form Body 
------------------------------------------------------------
discord.ApiError[50035]: Invalid Form Body, when running discord.api.createInteractionResponse via: POST createInteractionResponse
    at discordApiRequest (discord.js:95:25)
    at Object.createInteractionResponse (discord.js:471:24)
    at SlashCommandInteraction.respond (discord.js:4256:126)
    at SlashCommand.handler (script-369598024998977536.js:1908:27)
    at async SlashCommand._execute (discord.js:3824:25)
    at async discord.js:4017:25

Extended Message:
  {
    "code": 50035,
    "errors": {
      "data": {
        "embeds": {
          "0": {
            "image": {
              "url": {
                "_errors": [
                  {
                    "code": "URL_TYPE_INVALID_SCHEME",
                    "message": "Scheme \"h\" is not supported. Scheme must be one of ('http', 'https')."
                  }
                ]
              }
            }
          }
        }
      }
    },
    "message": "Invalid Form Body"
  } 
  ```
  
Any help would be much appreciated. As there is no explanation of how to get the url in the docs.

**Comment by JSH32** [comment]
You must make a request to `https://api.waifu.pics/type/endpoint`. You forgot to prepend `api` subdomain, `https://waifu.pics/api` also works.

**Comment by ghost** [comment]
> 

I tried that one just a couple minutes ago and it just hangs and times out. I'm guessing my url method might be wrong.

--- Edit

nevermind I got it. Your fix combined with a slight edit to my url part worked perfectly! ty
